### ISSUE TITLE
Cannot center a section

### ISSUE THREAD

**Issue by hoanganhduong** [hoanganhduong/modularity-mindfulness#1]
I cant center this part though Ive tried float, vertically-align and flexbox
<img width="929" alt="Screen Shot 2020-10-01 at 11 34 02 AM" src="https://user-images.githubusercontent.com/55412298/94830896-0d8c8980-03da-11eb-8ee8-e7132d850a25.png">
@HannahDelaney @hellachella @JessJodoin

**Comment by JessJodoin** [comment]
On your `.section` in main.css , add auto to the margin

`margin: 1rem auto;`

**Comment by hoanganhduong** [comment]
I tried that, it still doesnt work

**Comment by hoanganhduong** [comment]
nvm, i forgot to save before checking back on chrome, it works!
