### ISSUE TITLE
Cant position name of site vertically

### ISSUE THREAD

**Issue by hoanganhduong** [hoanganhduong/modularity-mindfulness#2]
<img width="313" alt="Screen Shot 2020-10-01 at 12 54 34 PM" src="https://user-images.githubusercontent.com/55412298/94839734-66155400-03e5-11eb-90c1-08973d6e5573.png">
I'm having trouble putting Rock Gardens under the Japanese phrase
@JessJodoin

**Comment by JessJodoin** [comment]
Try setting it up in the index like this:
```
<h1>
   <i lang="ja">枯山水</i>
   <span>Rock Gardens</span>
 </h1>
```

and target it in css like this:
```
h1 {
  display: flex;
  flex-direction: column;
  align-items: center;

  margin: 0;
  padding: 0 1rem;
  font-size: 2rem;
}

h1 span {
  font-size: 1.125rem;
}
```
